/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ecommerce.projeto.view;

import br.com.ecommerce.projeto.controller.FuncionarioController;
import br.com.ecommerce.projeto.model.domain.Cidade;
import br.com.ecommerce.projeto.model.domain.Funcionario;
import br.com.ecommerce.projeto.model.domain.enums.Estado;
import br.com.ecommerce.projeto.model.domain.enums.TipoFuncionario;
import br.com.ecommerce.projeto.model.services.GerenteService;
import br.com.ecommerce.projeto.model.services.VendedorService;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.io.IOException;

/**
 *
 * @author vinib
 */
public class telaFuncionarioGerente extends javax.swing.JFrame {

    /**
     * Creates new form telaProdutoGerente
     */
    public telaFuncionarioGerente() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btEditar = new javax.swing.JButton();
        btAdd = new javax.swing.JButton();
        btRemover = new javax.swing.JButton();
        lbProduto = new javax.swing.JLabel();
        tfMatricula = new javax.swing.JTextField();
        tfNome = new javax.swing.JTextField();
        lbCodigo = new javax.swing.JLabel();
        lbQuantidade = new javax.swing.JLabel();
        tfEmail = new javax.swing.JTextField();
        lbValor = new javax.swing.JLabel();
        tfCidade = new javax.swing.JTextField();
        lbEstado = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbProdutoGerente = new javax.swing.JTable();
        lbSalario = new javax.swing.JLabel();
        tfSalario = new javax.swing.JTextField();
        lbFuncao = new javax.swing.JLabel();
        btCalcBonus = new javax.swing.JButton();
        optEstado = new javax.swing.JComboBox<>();
        optFuncao = new javax.swing.JComboBox<>();
        btVoltar = new javax.swing.JButton();
        btRemoverTodos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(850, 660));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setMaximumSize(new java.awt.Dimension(670, 410));
        jPanel1.setMinimumSize(new java.awt.Dimension(850, 660));
        jPanel1.setPreferredSize(new java.awt.Dimension(850, 660));

        btEditar.setText("Editar");
        btEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    btEditarActionPerformed(evt);
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        });

        btAdd.setText("Adicionar");
        btAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    btAddActionPerformed(evt);
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        });

        btRemover.setText("Remover");
        btRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    btRemoverActionPerformed(evt);
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        });

        lbProduto.setText("Matricula");

        lbCodigo.setText("Nome");

        lbQuantidade.setText("E-mail");

        lbValor.setText("Cidade");

        lbEstado.setText("Estado");

        tbProdutoGerente.setBackground(new java.awt.Color(204, 204, 204));
        tbProdutoGerente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Matricula", "Nome", "E-mail", "Cidade", "Estado", "Salario", "Funcao"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbProdutoGerente.setSelectionBackground(new java.awt.Color(51, 51, 255));
        jScrollPane1.setViewportView(tbProdutoGerente);
        if (tbProdutoGerente.getColumnModel().getColumnCount() > 0) {
            tbProdutoGerente.getColumnModel().getColumn(4).setResizable(false);
            tbProdutoGerente.getColumnModel().getColumn(4).setPreferredWidth(50);
            tbProdutoGerente.getColumnModel().getColumn(5).setPreferredWidth(50);
        }

        lbSalario.setText("Salario");

        tfSalario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSalarioActionPerformed(evt);
            }
        });

        lbFuncao.setText("Funcao");

        btCalcBonus.setText("Calcular Bonus");
        btCalcBonus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCalcBonusActionPerformed(evt);
            }
        });

        optEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AM", "AP", "BA", "CE", "DF", "ES", "GO", "MA", "MG", "MS", "MT", "PA", "PB", "PE", "PI", "PR", "RJ", "RN", "RO", "RR", "RS", "SC", "SE", "SP", "TO" }));

        optFuncao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gerente", "Vendedor" }));

        btVoltar.setText("Voltar");
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });

        btRemoverTodos.setText("Remover todos");
        btRemoverTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    btRemoverTodosActionPerformed(evt);
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btCalcBonus, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                .addComponent(lbProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tfMatricula)
                                .addComponent(lbCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tfNome)
                                .addComponent(lbQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tfEmail)
                                .addComponent(lbValor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tfCidade)
                                .addComponent(lbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btRemover, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tfSalario)
                                .addComponent(optEstado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(optFuncao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btRemoverTodos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbFuncao, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbProduto)
                        .addGap(6, 6, 6)
                        .addComponent(tfMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(lbCodigo)
                        .addGap(6, 6, 6)
                        .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(lbQuantidade)
                        .addGap(6, 6, 6)
                        .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(lbValor)
                        .addGap(6, 6, 6)
                        .addComponent(tfCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(lbEstado)
                        .addGap(8, 8, 8)
                        .addComponent(optEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbSalario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(lbFuncao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(optFuncao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(btRemoverTodos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btCalcBonus, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(btAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(btRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btVoltar)
                .addGap(79, 79, 79))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 790, 640);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAddActionPerformed(java.awt.event.ActionEvent evt) throws IOException {//GEN-FIRST:event_btAddActionPerformed
        String nome = tfNome.getText();
        String matricula = tfMatricula.getText();
        String salario = tfSalario.getText();
        String email = tfEmail.getText();
        String cidade = tfCidade.getText();
        String estado = optEstado.getSelectedItem().toString();
        verificaCampoCidade(cidade);
        verificaCampoEmail(email);
        verificaCampoMatricula(matricula);
        verificaCampoNome(nome);
        verificaCampoSalario(salario);
        Cidade city = new Cidade(cidade, Estado.valueOf(estado));
        TipoFuncionario tipo = TipoFuncionario.valueOf(optFuncao.toString());
        double sal = Double.parseDouble(salario);
        Funcionario funcionario = new Funcionario(matricula, nome, email, tipo, city, sal);
        FuncionarioController controller = new FuncionarioController();
        controller.save(funcionario);
        DefaultTableModel model = (DefaultTableModel) tbProdutoGerente.getModel();
        model.addRow(new Object[]{funcionario.getMatricula(), funcionario.getNome(),
                funcionario.getEmail(), funcionario.getCidade().getNome(),
                funcionario.getCidade().getEstado().getNome(),
                funcionario.getSalario(), funcionario.getTipo()});
    }//GEN-LAST:event_btAddActionPerformed

    private void tfSalarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSalarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSalarioActionPerformed

    private void btCalcBonusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCalcBonusActionPerformed
        DefaultTableModel model = (DefaultTableModel) tbProdutoGerente.getModel();
        Object data = model.getDataVector().elementAt(tbProdutoGerente.getSelectedRow());
        String[] dados = data.toString().split(",");
        String nome = dados[1];
        String matricula = dados[0];
        String email = dados[2];
        String cidade = dados[3];
        String estado = dados[4];
        String salario = dados[5];
        double sal = Double.parseDouble(salario);
        String funcao = dados[6];
        TipoFuncionario tipo = TipoFuncionario.valueOf(funcao);
        Cidade city = new Cidade(cidade, Estado.valueOf(estado));
        Funcionario funcionario = new Funcionario(matricula, nome, email, tipo, city, sal);
        if(funcionario.getTipo() == TipoFuncionario.Gerente){
            GerenteService service = new GerenteService(funcionario);
            double bonus = service.calculoBonus();
            JOptionPane.showMessageDialog(null, "Esse funcionario ganhara  "
                    + bonus+ " reais de bonus");
        }
        else if(funcionario.getTipo() ==TipoFuncionario.Vendedor){
            VendedorService service = new VendedorService(funcionario);
            double bonus = service.calculoBonus();
            JOptionPane.showMessageDialog(null, "Esse funcionario ganhara  "
                    + bonus+ " reais de bonus");
        }
    }//GEN-LAST:event_btCalcBonusActionPerformed

    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
        telaOpcoesGerente tela = new telaOpcoesGerente();
        tela.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btVoltarActionPerformed

    private void btRemoverActionPerformed(java.awt.event.ActionEvent evt) throws IOException {//GEN-FIRST:event_btRemoverActionPerformed
        FuncionarioController controller = new FuncionarioController();
        DefaultTableModel model = (DefaultTableModel) tbProdutoGerente.getModel();
        Object data = model.getDataVector().elementAt(tbProdutoGerente.getSelectedRow());
        String[] dados = data.toString().split(",");
        String matricula = dados[0];
        String nome = dados[1];
        String email = dados[2];
        String cidade = dados[3];
        String estado = dados[4];
        String salario = dados[5];
        String funcao = dados[6];
        double sal = Double.parseDouble(salario);
        Cidade city = new Cidade(cidade, Estado.valueOf(estado));
        TipoFuncionario tipo = TipoFuncionario.valueOf(funcao);
        Funcionario funcionario = new Funcionario(matricula, nome, email, tipo, city, sal);
        controller.delete(funcionario);
        model.removeRow(tbProdutoGerente.getSelectedRow());
    }//GEN-LAST:event_btRemoverActionPerformed

    private void btEditarActionPerformed(java.awt.event.ActionEvent evt) throws IOException {//GEN-FIRST:event_btEditarActionPerformed
        FuncionarioController controller = new FuncionarioController();
        DefaultTableModel model = (DefaultTableModel) tbProdutoGerente.getModel();
        Object data = model.getDataVector().elementAt(tbProdutoGerente.getSelectedRow());
        String[] dados = data.toString().split(",");
        String matricula = dados[0];
        String nome = dados[1];
        String email = dados[2];
        String cidade = dados[3];
        String estado = dados[4];
        String salario = dados[5];
        String funcao = dados[6];
        double sal = Double.parseDouble(salario);
        Cidade city = new Cidade(cidade, Estado.valueOf(estado));
        TipoFuncionario tipo = TipoFuncionario.valueOf(funcao);
        Funcionario funcionario = new Funcionario(matricula, nome, email, tipo, city, sal);
        controller.update(funcionario);
    }//GEN-LAST:event_btEditarActionPerformed

    private void btRemoverTodosActionPerformed(java.awt.event.ActionEvent evt) throws IOException {//GEN-FIRST:event_btRemoverTodosActionPerformed
        FuncionarioController controller = new FuncionarioController();
        controller.deleteAll();
        DefaultTableModel model = (DefaultTableModel) tbProdutoGerente.getModel();
        for(int i =0; i<model.getRowCount(); i++){
            model.removeRow(i);
        }
    }//GEN-LAST:event_btRemoverTodosActionPerformed

    private void verificaCampoNome(String var){
        if(var.isEmpty()){
            JOptionPane.showMessageDialog(null, "Campo Nome vazio!");
        }
        else{
            JOptionPane.showMessageDialog(null, "Campo Nome Preenchido com sucesso!");
        }
    }
    private void verificaCampoMatricula(String var){
        if(var.isEmpty()){
            JOptionPane.showMessageDialog(null, "Campo CPF ou CNPJ vazio!");
        }
        else{
            JOptionPane.showMessageDialog(null, "Campo CPF ou CNPJ Preenchido com sucesso!");
        }
    }
    private void verificaCampoEmail(String var){
        if(var.isEmpty()){
            JOptionPane.showMessageDialog(null, "Campo Email vazio!");
        }
        else{
            JOptionPane.showMessageDialog(null, "Campo Email Preenchido com sucesso!");
        }
    }
    private void verificaCampoCidade(String var){
        if(var.isEmpty()){
            JOptionPane.showMessageDialog(null, "Campo Cidade vazio!");
        }
        else{
            JOptionPane.showMessageDialog(null, "Campo Cidade Preenchido com sucesso!");
        }
    }
    private void verificaCampoSalario(String var){
        try{
            Double.parseDouble(var);
        }catch (NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Campo salario preenchido de forma invalida!");

        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaFuncionarioGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaFuncionarioGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaFuncionarioGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaFuncionarioGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaFuncionarioGerente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdd;
    private javax.swing.JButton btCalcBonus;
    private javax.swing.JButton btEditar;
    private javax.swing.JButton btRemover;
    private javax.swing.JButton btRemoverTodos;
    private javax.swing.JButton btVoltar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbCodigo;
    private javax.swing.JLabel lbEstado;
    private javax.swing.JLabel lbFuncao;
    private javax.swing.JLabel lbProduto;
    private javax.swing.JLabel lbQuantidade;
    private javax.swing.JLabel lbSalario;
    private javax.swing.JLabel lbValor;
    private javax.swing.JComboBox<String> optEstado;
    private javax.swing.JComboBox<String> optFuncao;
    private javax.swing.JTable tbProdutoGerente;
    private javax.swing.JTextField tfCidade;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfMatricula;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextField tfSalario;
    // End of variables declaration//GEN-END:variables
}
