/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ecommerce.projeto.view;

import br.com.ecommerce.projeto.controller.ClienteController;
import br.com.ecommerce.projeto.model.domain.Cidade;
import br.com.ecommerce.projeto.model.domain.Cliente;
import br.com.ecommerce.projeto.model.domain.enums.Estado;
import br.com.ecommerce.projeto.model.domain.enums.TipoCliente;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.io.IOException;

/**
 *
 * @author vinib
 */
public class telaClienteGerente extends javax.swing.JFrame {

    /**
     * Creates new form telaProdutoGerente
     */

    TipoCliente tipo;
    public telaClienteGerente() {
        initComponents();
        setLocationRelativeTo(this);
        ButtonGroup group = new ButtonGroup();
        group.add(rbPFisica);
        group.add(rbPJuridica);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btEditar = new javax.swing.JButton();
        btAdd = new javax.swing.JButton();
        btRemover = new javax.swing.JButton();
        lbProduto = new javax.swing.JLabel();
        tfCPF = new javax.swing.JTextField();
        tfNome = new javax.swing.JTextField();
        lbCodigo = new javax.swing.JLabel();
        lbQuantidade = new javax.swing.JLabel();
        tfEmail = new javax.swing.JTextField();
        lbValor = new javax.swing.JLabel();
        tfCidade = new javax.swing.JTextField();
        lbEstado = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbClienteGerente = new javax.swing.JTable();
        optEstado = new javax.swing.JComboBox<>();
        rbPFisica = new javax.swing.JRadioButton();
        rbPJuridica = new javax.swing.JRadioButton();
        btRemoverTodos = new javax.swing.JButton();
        btVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(790, 700));
        setPreferredSize(new java.awt.Dimension(790, 700));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setMaximumSize(new java.awt.Dimension(670, 410));
        jPanel1.setMinimumSize(new java.awt.Dimension(790, 660));
        jPanel1.setPreferredSize(new java.awt.Dimension(790, 660));

        btEditar.setText("Editar");
        btEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarActionPerformed(evt);
            }
        });

        btAdd.setText("Adicionar");
        btAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddActionPerformed(evt);
            }
        });

        btRemover.setText("Remover");
        btRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoverActionPerformed(evt);
            }
        });

        lbProduto.setText("CPF/CNPJ");

        lbCodigo.setText("Nome");

        lbQuantidade.setText("E-mail");

        lbValor.setText("Cidade");

        lbEstado.setText("Estado");

        tbClienteGerente.setBackground(new java.awt.Color(204, 204, 204));
        tbClienteGerente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "CPF/CNPJ", "Nome", "E-mail", "Cidade", "Estado", "PF/PJ"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbClienteGerente.setSelectionBackground(new java.awt.Color(51, 51, 255));
        jScrollPane1.setViewportView(tbClienteGerente);
        if (tbClienteGerente.getColumnModel().getColumnCount() > 0) {
            tbClienteGerente.getColumnModel().getColumn(4).setResizable(false);
            tbClienteGerente.getColumnModel().getColumn(4).setPreferredWidth(50);
        }

        optEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AM", "AP", "BA", "CE", "DF", "ES", "GO", "MA", "MG", "MS", "MT", "PA", "PB", "PE", "PI", "PR", "RJ", "RN", "RO", "RR", "RS", "SC", "SE", "SP", "TO" }));

        rbPFisica.setText("Pessoa Fisica");
        rbPFisica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPFisicaActionPerformed(evt);
            }
        });

        rbPJuridica.setText("Pessoa Juridica");
        rbPJuridica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPJuridicaActionPerformed(evt);
            }
        });

        btRemoverTodos.setText("Remover todos");
        btRemoverTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoverTodosActionPerformed(evt);
            }
        });

        btVoltar.setText("Voltar");
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btRemoverTodos, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tfCPF)
                        .addComponent(lbCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfNome)
                        .addComponent(lbQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfEmail)
                        .addComponent(lbValor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfCidade)
                        .addComponent(lbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                        .addComponent(btRemover, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(optEstado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbProduto)
                        .addComponent(btVoltar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(rbPFisica, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbPJuridica))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbProduto)
                        .addGap(6, 6, 6)
                        .addComponent(tfCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(lbCodigo)
                        .addGap(6, 6, 6)
                        .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(lbQuantidade)
                        .addGap(6, 6, 6)
                        .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(lbValor)
                        .addGap(6, 6, 6)
                        .addComponent(tfCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(lbEstado)
                        .addGap(8, 8, 8)
                        .addComponent(optEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(rbPFisica)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbPJuridica)
                        .addGap(67, 67, 67)
                        .addComponent(btRemoverTodos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(btRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(btEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 790, 640);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAddActionPerformed(java.awt.event.ActionEvent evt) throws IOException {//GEN-FIRST:event_btAddActionPerformed
        verificaCampoNome(tfNome.getText());
        verificaCampoCpfOuCNPJ(tfCPF.getText());
        verificaCampoEmail(tfEmail.getText());
        verificaCampoCidade(tfCidade.getText());
        String nome = tfNome.getText();
        String cpfOuCnpj = tfCPF.getText();
        String email = tfEmail.getText();
        String cidade = tfCidade.getText();
        String estado = optEstado.getSelectedItem().toString();
        TipoCliente type = this.tipo;
        Cidade city = new Cidade(cidade, Estado.valueOf(estado));
        Cliente cliente = new Cliente(nome, email, cpfOuCnpj, type, city);
        ClienteController controller = new ClienteController();
        controller.save(cliente);
        DefaultTableModel model = (DefaultTableModel) tbClienteGerente.getModel();
        model.addRow(new Object[]{cliente.getCpfOuCnpj(), cliente.getNome(),
                cliente.getEmail(), cliente.getCidade().getNome(),
                cliente.getCidade().getEstado().getNome(), cliente.getTipo()});

    }//GEN-LAST:event_btAddActionPerformed

    private void rbPFisicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPFisicaActionPerformed
        if(rbPJuridica.isSelected()){
            this.tipo = TipoCliente.PESSOAJURIDICA;
        }
    }//GEN-LAST:event_rbPFisicaActionPerformed

    private void rbPJuridicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPJuridicaActionPerformed
        if(rbPFisica.isSelected()){
            this.tipo = TipoCliente.PESSOAFISICA;
        }
    }//GEN-LAST:event_rbPJuridicaActionPerformed

    private void btRemoverActionPerformed(java.awt.event.ActionEvent evt) throws IOException {//GEN-FIRST:event_btRemoverActionPerformed
        DefaultTableModel model = (DefaultTableModel) tbClienteGerente.getModel();
        Object data = model.getDataVector().elementAt(tbClienteGerente.getSelectedRow());
        String[] dados = data.toString().split(",");
        String cpfOuCnpj = dados[0];
        String nome = dados[1];
        String email = dados[2];
        String cidade = dados[3];
        String estado = dados[4];
        String tipoCli = dados[5];
        Cidade city = new Cidade(cidade, Estado.valueOf(estado));
        TipoCliente type = TipoCliente.valueOf(tipoCli);
        Cliente cliente = new Cliente(nome, email, cpfOuCnpj, type, city);
        ClienteController controller = new ClienteController();
        controller.delete(cliente);
        model.removeRow(tbClienteGerente.getSelectedRow());
    }//GEN-LAST:event_btRemoverActionPerformed

    private void btEditarActionPerformed(java.awt.event.ActionEvent evt) throws IOException {//GEN-FIRST:event_btEditarActionPerformed
        DefaultTableModel model = (DefaultTableModel) tbClienteGerente.getModel();
        Object data = model.getDataVector().elementAt(tbClienteGerente.getSelectedRow());
        String[] dados = data.toString().split(",");
        String cpfOuCnpj = dados[0];
        String nome = dados[1];
        String email = dados[2];
        String cidade = dados[3];
        String estado = dados[4];
        String tipoCli = dados[5];
        Cidade city = new Cidade(cidade, Estado.valueOf(estado));
        TipoCliente type = TipoCliente.valueOf(tipoCli);
        Cliente cliente = new Cliente(nome, email, cpfOuCnpj, type, city);
        ClienteController controller = new ClienteController();
        controller.update(cliente);
    }//GEN-LAST:event_btEditarActionPerformed

    private void btRemoverTodosActionPerformed(java.awt.event.ActionEvent evt) throws IOException {//GEN-FIRST:event_btRemoverTodosActionPerformed
        ClienteController controller = new ClienteController();
        controller.deleteAll();
        DefaultTableModel model = (DefaultTableModel) tbClienteGerente.getModel();
        for(int i =0; i<model.getRowCount(); i++){
            model.removeRow(i);
        }
    }//GEN-LAST:event_btRemoverTodosActionPerformed

    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
        telaOpcoesGerente tela = new telaOpcoesGerente();
        tela.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btVoltarActionPerformed

    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btEditar1ActionPerformed

    private void verificaCampoNome(String var){
        if(var.isEmpty()){
            JOptionPane.showMessageDialog(null, "Campo Nome vazio!");
        }
        else{
            JOptionPane.showMessageDialog(null, "Campo Nome Preenchido com sucesso!");
        }
    }
    private void verificaCampoCpfOuCNPJ(String var){
        if(var.isEmpty()){
            JOptionPane.showMessageDialog(null, "Campo CPF ou CNPJ vazio!");
        }
        else{
            JOptionPane.showMessageDialog(null, "Campo CPF ou CNPJ Preenchido com sucesso!");
        }
    }
    private void verificaCampoEmail(String var){
        if(var.isEmpty()){
            JOptionPane.showMessageDialog(null, "Campo Email vazio!");
        }
        else{
            JOptionPane.showMessageDialog(null, "Campo Email Preenchido com sucesso!");
        }
    }
    private void verificaCampoCidade(String var){
        if(var.isEmpty()){
            JOptionPane.showMessageDialog(null, "Campo Cidade vazio!");
        }
        else{
            JOptionPane.showMessageDialog(null, "Campo Cidade Preenchido com sucesso!");
        }
    }

    /**
     * @param args the command line arguments
     */


    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaClienteGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaClienteGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaClienteGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaClienteGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaClienteGerente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdd;
    private javax.swing.JButton btEditar;
    private javax.swing.JButton btRemover;
    private javax.swing.JButton btRemoverTodos;
    private javax.swing.JButton btVoltar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbCodigo;
    private javax.swing.JLabel lbEstado;
    private javax.swing.JLabel lbProduto;
    private javax.swing.JLabel lbQuantidade;
    private javax.swing.JLabel lbValor;
    private javax.swing.JComboBox<String> optEstado;
    private javax.swing.JRadioButton rbPFisica;
    private javax.swing.JRadioButton rbPJuridica;
    private javax.swing.JTable tbClienteGerente;
    private javax.swing.JTextField tfCPF;
    private javax.swing.JTextField tfCidade;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfNome;
    // End of variables declaration//GEN-END:variables
}
